name: Deploy Windows Service

on:
  push:
    branches:
      - main  # Change this based on your branch strategy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows runner for Windows Service deployment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Package (if stored in GitHub Packages)
        run: |
          gh release download latest --pattern "sample-package.zip" --repo <your-org/your-repo>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Package
        run: |
          Expand-Archive -Path sample-package.zip -DestinationPath C:\deploy\sample-app -Force

      - name: Install Windows Service
        run: |
          $serviceName = "SampleAppService"
          $exePath = "C:\deploy\sample-app\YourService.exe"

          if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
            Stop-Service -Name $serviceName -Force
            sc.exe delete $serviceName
          }

          sc.exe create $serviceName binPath= $exePath start= auto
          Start-Service -Name $serviceName

      - name: Verify Service Status
        run: Get-Service -Name "SampleAppService"
