name: Deploy Windows Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Switch to self-hosted for admin rights

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify Deployment Package
        shell: powershell
        run: |
          $servicePath = "C:\Deploy\sample-package.exe"
          if (-Not (Test-Path $servicePath)) {
            Write-Host "ERROR: Deployment package not found at $servicePath"
            exit 1
          }

      - name: Install Windows Service with NSSM
        shell: powershell
        run: |
          $nssm = "C:\nssm\nssm.exe"
          $serviceName = "SampleWindowsService"
          $servicePath = "C:\Deploy\sample-package.exe"

          if (Test-Path $servicePath) {
            & $nssm install $serviceName $servicePath
            & $nssm set $serviceName Start SERVICE_AUTO_START
            & $nssm start $serviceName
          } else {
            Write-Host "ERROR: Service executable not found!"
            exit 1
          }

      - name: Verify Service Status
        shell: powershell
        run: |
          Get-Service -Name "SampleWindowsService"
